exports.ERR_DUPLICATE_EMAIL = 'ERR_DUPLICATE_EMAIL';
exports.ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
exports.ERROR_INVALID_PASSWORD = 'ERROR_INVALID_PASSWORD';
exports.ERROR_INVALID_TOKEN = 'ERROR_INVALID_TOKEN';
